[workspace]
resolver = "2"
members = [
    "packages/konjingjing",
    "packages/konjingjing-python",
    "packages/konjingjing-node",
]

[workspace.package]
version = "0.2.0"
authors = ["Nutchanon Ninyawee <me@nutchanon.org>"]
license = "ISC"
repository = "https://github.com/ninyawee/konjingjing"
