[package]
name = "konjingjing-wasm"
version.workspace = true
authors.workspace = true
license.workspace = true
repository.workspace = true
edition = "2021"
description = "Thai Citizen ID validation library - WebAssembly build"

[lib]
crate-type = ["cdylib", "rlib"]

[dependencies]
konjingjing = { path = "../konjingjing" }
wasm-bindgen = "0.2"
serde = { version = "1.0", features = ["derive"] }
serde-wasm-bindgen = "0.6"
tsify-next = { version = "0.5", features = ["js"] }

[dev-dependencies]
wasm-bindgen-test = "0.3"
